# Generated by Django 2.2.7 on 2019-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('days', models.CharField(max_length=5)),
                ('arrivetime', models.DateTimeField()),
                ('roomnumber', models.CharField(max_length=5)),
            ],
        ),
    ]
