# Generated by Django 2.2.7 on 2019-12-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrivetime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roomnumber',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
