# Generated by Django 2.2.7 on 2019-12-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20191217_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='days',
            new_name='Number of days',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='roomnumber',
            new_name='Room Number',
        ),
    ]
