# Generated by Django 2.2.7 on 2019-12-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20191217_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Number of days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Room Number',
            field=models.IntegerField(),
        ),
    ]
