# Generated by Django 2.2.7 on 2019-12-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20191217_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Room Number',
            new_name='RoomNumber',
        ),
    ]
