# Generated by Django 2.2.7 on 2019-12-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20191217_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='roomnumber',
            new_name='room_number',
        ),
    ]
