# Generated by Django 2.2.7 on 2019-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_booking_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='roomnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
