# Generated by Django 2.2.7 on 2019-12-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_booking_roomnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('price', models.IntegerField()),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
